/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 *  contributor license agreements.  The ASF licenses this file to You
 * under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.  For additional information regarding
 * copyright in this work, please see the NOTICE file in the top level
 * directory of this distribution.
 */

package org.apache.roller.weblogger.pojos;

import java.sql.Timestamp;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for {@link WeblogEntryComment}.
 *
 * <p>Covers: default field values, computed boolean properties, timestamp
 * helper, toString format, equals/hashCode contract.</p>
 */
class WeblogEntryCommentTest {

    private WeblogEntryComment comment;

    @BeforeEach
    void setUp() {
        comment = new WeblogEntryComment();
    }

    // ---------------------------------------------------------------- Construction defaults

    @Test
    void defaultStatus_isApproved() {
        assertEquals(WeblogEntryComment.ApprovalStatus.APPROVED, comment.getStatus());
    }

    @Test
    void defaultNotify_isFalse() {
        assertFalse(comment.getNotify());
    }

    @Test
    void defaultContentType_isTextPlain() {
        assertEquals("text/plain", comment.getContentType());
    }

    @Test
    void id_isAutoGeneratedAndNotBlank() {
        assertNotNull(comment.getId());
        assertFalse(comment.getId().isBlank());
    }

    @Test
    void twoFreshComments_haveDifferentIds() {
        assertNotEquals(new WeblogEntryComment().getId(), new WeblogEntryComment().getId());
    }

    @Test
    void allOptionalFields_areNullByDefault() {
        assertNull(comment.getName());
        assertNull(comment.getEmail());
        assertNull(comment.getUrl());
        assertNull(comment.getContent());
        assertNull(comment.getPostTime());
        assertNull(comment.getRemoteHost());
        assertNull(comment.getReferrer());
        assertNull(comment.getUserAgent());
        assertNull(comment.getPlugins());
        assertNull(comment.getWeblogEntry());
    }

    // ---------------------------------------------------------------- Scalar setters / getters

    @Test
    void setAndGetName() {
        comment.setName("Alice");
        assertEquals("Alice", comment.getName());
    }

    @Test
    void setAndGetEmail() {
        comment.setEmail("alice@example.com");
        assertEquals("alice@example.com", comment.getEmail());
    }

    @Test
    void setAndGetUrl() {
        comment.setUrl("https://example.com");
        assertEquals("https://example.com", comment.getUrl());
    }

    @Test
    void setAndGetContent() {
        comment.setContent("Great article!");
        assertEquals("Great article!", comment.getContent());
    }

    @Test
    void setAndGetRemoteHost() {
        comment.setRemoteHost("192.168.1.5");
        assertEquals("192.168.1.5", comment.getRemoteHost());
    }

    @Test
    void setAndGetReferrer() {
        comment.setReferrer("https://referrer.example.com");
        assertEquals("https://referrer.example.com", comment.getReferrer());
    }

    @Test
    void setAndGetUserAgent() {
        comment.setUserAgent("Mozilla/5.0");
        assertEquals("Mozilla/5.0", comment.getUserAgent());
    }

    @Test
    void setAndGetPlugins() {
        comment.setPlugins("plugin1,plugin2");
        assertEquals("plugin1,plugin2", comment.getPlugins());
    }

    @Test
    void setAndGetContentType() {
        comment.setContentType("text/html");
        assertEquals("text/html", comment.getContentType());
    }

    @Test
    void setAndGetNotify() {
        comment.setNotify(Boolean.TRUE);
        assertTrue(comment.getNotify());
    }

    // ---------------------------------------------------------------- ApprovalStatus computed properties

    @Test
    void getApproved_trueWhenApproved() {
        comment.setStatus(WeblogEntryComment.ApprovalStatus.APPROVED);
        assertTrue(comment.getApproved());
        assertFalse(comment.getSpam());
        assertFalse(comment.getPending());
    }

    @Test
    void getSpam_trueWhenSpam() {
        comment.setStatus(WeblogEntryComment.ApprovalStatus.SPAM);
        assertTrue(comment.getSpam());
        assertFalse(comment.getApproved());
        assertFalse(comment.getPending());
    }

    @Test
    void getPending_trueWhenPending() {
        comment.setStatus(WeblogEntryComment.ApprovalStatus.PENDING);
        assertTrue(comment.getPending());
        assertFalse(comment.getApproved());
        assertFalse(comment.getSpam());
    }

    @Test
    void disapprovedStatus_noBooleanHelperIsTrue() {
        comment.setStatus(WeblogEntryComment.ApprovalStatus.DISAPPROVED);
        assertFalse(comment.getApproved());
        assertFalse(comment.getSpam());
        assertFalse(comment.getPending());
    }

    @Test
    void setStatus_reflectsNewValue() {
        comment.setStatus(WeblogEntryComment.ApprovalStatus.SPAM);
        assertEquals(WeblogEntryComment.ApprovalStatus.SPAM, comment.getStatus());
        comment.setStatus(WeblogEntryComment.ApprovalStatus.APPROVED);
        assertEquals(WeblogEntryComment.ApprovalStatus.APPROVED, comment.getStatus());
    }

    // ---------------------------------------------------------------- getTimestamp()

    @Test
    void getTimestamp_nullWhenPostTimeNotSet() {
        assertNull(comment.getTimestamp());
    }

    @Test
    void getTimestamp_returnsMillisAsString() {
        long now = System.currentTimeMillis();
        comment.setPostTime(new Timestamp(now));
        assertEquals(Long.toString(now), comment.getTimestamp());
    }

    @Test
    void getTimestamp_isConsistentWithPostTime() {
        Timestamp ts = new Timestamp(1_700_000_000_000L);
        comment.setPostTime(ts);
        assertEquals("1700000000000", comment.getTimestamp());
    }

    // ---------------------------------------------------------------- toString()

    @Test
    void toString_containsId() {
        assertTrue(comment.toString().contains(comment.getId()));
    }

    @Test
    void toString_containsNameWhenSet() {
        comment.setName("Bob");
        assertTrue(comment.toString().contains("Bob"));
    }

    @Test
    void toString_containsEmailWhenSet() {
        comment.setEmail("bob@example.com");
        assertTrue(comment.toString().contains("bob@example.com"));
    }

    @Test
    void toString_hasBraceFormat() {
        String s = comment.toString();
        assertTrue(s.startsWith("{") && s.endsWith("}"),
                "toString should be wrapped in braces, was: " + s);
    }

    // ---------------------------------------------------------------- equals() and hashCode()

    @Test
    void equals_sameInstance_isTrue() {
        assertEquals(comment, comment);
    }

    @Test
    void equals_null_isFalse() {
        assertNotEquals(null, comment);
    }

    @Test
    void equals_differentType_isFalse() {
        assertNotEquals("not a comment", comment);
    }

    @Test
    void equals_sameNameAndPostTimeAndEntry_isTrue() {
        Timestamp ts = new Timestamp(1_000_000L);
        WeblogEntry entry = new WeblogEntry();

        WeblogEntryComment c1 = new WeblogEntryComment();
        c1.setName("Alice");
        c1.setPostTime(ts);
        c1.setWeblogEntry(entry);

        WeblogEntryComment c2 = new WeblogEntryComment();
        c2.setName("Alice");
        c2.setPostTime(ts);
        c2.setWeblogEntry(entry);

        assertEquals(c1, c2);
    }

    @Test
    void equals_differentName_isFalse() {
        Timestamp ts = new Timestamp(1_000_000L);

        WeblogEntryComment c1 = new WeblogEntryComment();
        c1.setName("Alice");
        c1.setPostTime(ts);

        WeblogEntryComment c2 = new WeblogEntryComment();
        c2.setName("Bob");
        c2.setPostTime(ts);

        assertNotEquals(c1, c2);
    }

    @Test
    void equals_differentPostTime_isFalse() {
        WeblogEntryComment c1 = new WeblogEntryComment();
        c1.setName("Alice");
        c1.setPostTime(new Timestamp(1_000L));

        WeblogEntryComment c2 = new WeblogEntryComment();
        c2.setName("Alice");
        c2.setPostTime(new Timestamp(2_000L));

        assertNotEquals(c1, c2);
    }

    @Test
    void hashCode_equalObjectsHaveSameHashCode() {
        Timestamp ts = new Timestamp(5_000L);
        WeblogEntry entry = new WeblogEntry();

        WeblogEntryComment c1 = new WeblogEntryComment();
        c1.setName("Carol");
        c1.setPostTime(ts);
        c1.setWeblogEntry(entry);

        WeblogEntryComment c2 = new WeblogEntryComment();
        c2.setName("Carol");
        c2.setPostTime(ts);
        c2.setWeblogEntry(entry);

        assertEquals(c1.hashCode(), c2.hashCode());
    }

    @Test
    void hashCode_isStable_acrossMultipleCalls() {
        comment.setName("Dave");
        int h1 = comment.hashCode();
        int h2 = comment.hashCode();
        assertEquals(h1, h2);
    }

    // ---------------------------------------------------------------- ApprovalStatus enum

    @Test
    void approvalStatusEnum_hasFourValues() {
        assertEquals(4, WeblogEntryComment.ApprovalStatus.values().length);
    }
}
